/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    soins: Soin;
    formations: Formation;
    temoignages: Temoignage;
    media: Media;
    documents: Document;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    soins: SoinsSelect<false> | SoinsSelect<true>;
    formations: FormationsSelect<false> | FormationsSelect<true>;
    temoignages: TemoignagesSelect<false> | TemoignagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    accueil: Accueil;
    'a-propos': APropo;
    'coordonnees-site': CoordonneesSite;
  };
  globalsSelect: {
    accueil: AccueilSelect<false> | AccueilSelect<true>;
    'a-propos': AProposSelect<false> | AProposSelect<true>;
    'coordonnees-site': CoordonneesSiteSelect<false> | CoordonneesSiteSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Gérez ici les soins affichés sur la page publique « Soins ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "soins".
 */
export interface Soin {
  id: number;
  /**
   * Décochez cette case pour masquer temporairement ce soin.
   */
  active?: boolean | null;
  /**
   * Les plus petits nombres apparaissent en premier.
   */
  order?: number | null;
  /**
   * Le titre principal affiché sur le site.
   */
  title: string;
  /**
   * La courte phrase affichée juste au-dessus du titre.
   */
  eyebrow?: string | null;
  /**
   * Présentez le soin en quelques phrases simples.
   */
  description: string;
  /**
   * Informations facultatives affichées sous la description principale.
   */
  details?: string | null;
  /**
   * Sélectionnez une image existante ou importez-en une nouvelle. Sans image, le site conserve sa photo actuelle.
   */
  image?: (number | null) | Media;
  /**
   * Vous pouvez réordonner les lignes par glisser-déposer.
   */
  durations?:
    | {
        /**
         * Exemple : 60 min
         */
        duration: string;
        /**
         * Exemple : 75 €
         */
        price: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bibliothèque des images utilisées dans les soins et sur le site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Décrivez brièvement l’image pour les personnes qui ne peuvent pas la voir.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Gérez ici les formations affichées sur la page publique « Formations ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formations".
 */
export interface Formation {
  id: number;
  /**
   * Décochez cette case pour masquer temporairement cette formation.
   */
  active?: boolean | null;
  /**
   * Les plus petits nombres apparaissent en premier.
   */
  order?: number | null;
  /**
   * Le grand titre affiché dans la fiche.
   */
  title: string;
  /**
   * Affiché dans la colonne colorée. Si ce champ est vide, le nom complet sera utilisé.
   */
  shortTitle?: string | null;
  /**
   * La courte phrase affichée au-dessus du titre court.
   */
  eyebrow?: string | null;
  /**
   * Présentez le contenu et l’esprit de la formation.
   */
  description: string;
  /**
   * Exemple : 2 jours
   */
  duration?: string | null;
  /**
   * Exemple : 14 h
   */
  hours?: string | null;
  /**
   * Exemple : À partir de 450 € / personne
   */
  price?: string | null;
  /**
   * Les quatre premiers objectifs sont affichés sur la page publique.
   */
  objectives?:
    | {
        objective: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Cochez si la formation peut être suivie individuellement.
   */
  individual?: boolean | null;
  /**
   * Laissez vide si aucune limite ne doit être affichée.
   */
  maxParticipants?: number | null;
  /**
   * Exemple : Hébergement sur place possible : 50 € / nuit
   */
  accommodation?: string | null;
  /**
   * Seuls les documents actifs sont proposés dans cette liste.
   */
  documents?: (number | Document)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bibliothèque des documents téléchargeables proposés sur le site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * Seuls les documents cochés peuvent être proposés publiquement.
   */
  active?: boolean | null;
  /**
   * Les plus petits nombres apparaissent en premier.
   */
  order?: number | null;
  title: string;
  description?: string | null;
  category: 'formation' | 'soin' | 'accueil' | 'contact' | 'autre';
  /**
   * Facultatif, par exemple : 2026 ou v2.
   */
  version?: string | null;
  /**
   * Facultatif.
   */
  documentDate?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Gérez les témoignages affichés sur la page d’accueil.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "temoignages".
 */
export interface Temoignage {
  id: number;
  active?: boolean | null;
  /**
   * Les plus petits nombres apparaissent en premier.
   */
  order?: number | null;
  name: string;
  text: string;
  /**
   * Facultatif, par exemple : soin ou formation.
   */
  context?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestion des comptes autorisés à accéder à l’administration.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Nom affiché pour identifier facilement ce compte.
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'soins';
        value: number | Soin;
      } | null)
    | ({
        relationTo: 'formations';
        value: number | Formation;
      } | null)
    | ({
        relationTo: 'temoignages';
        value: number | Temoignage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "soins_select".
 */
export interface SoinsSelect<T extends boolean = true> {
  active?: T;
  order?: T;
  title?: T;
  eyebrow?: T;
  description?: T;
  details?: T;
  image?: T;
  durations?:
    | T
    | {
        duration?: T;
        price?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formations_select".
 */
export interface FormationsSelect<T extends boolean = true> {
  active?: T;
  order?: T;
  title?: T;
  shortTitle?: T;
  eyebrow?: T;
  description?: T;
  duration?: T;
  hours?: T;
  price?: T;
  objectives?:
    | T
    | {
        objective?: T;
        id?: T;
      };
  individual?: T;
  maxParticipants?: T;
  accommodation?: T;
  documents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "temoignages_select".
 */
export interface TemoignagesSelect<T extends boolean = true> {
  active?: T;
  order?: T;
  name?: T;
  text?: T;
  context?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  active?: T;
  order?: T;
  title?: T;
  description?: T;
  category?: T;
  version?: T;
  documentDate?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Modifiez les textes de l’accueil sans changer sa mise en page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accueil".
 */
export interface Accueil {
  id: number;
  heroEyebrow?: string | null;
  heroTitleLine1?: string | null;
  heroTitleLine2?: string | null;
  heroTitleAccent?: string | null;
  heroText?: string | null;
  introEyebrow?: string | null;
  introTitle?: string | null;
  introText?: string | null;
  careEyebrow?: string | null;
  careLabel?: string | null;
  careTitle?: string | null;
  careText?: string | null;
  immersiveLine1?: string | null;
  immersiveLine2?: string | null;
  immersiveAccent?: string | null;
  trainingEyebrow?: string | null;
  trainingLabel?: string | null;
  trainingTitle?: string | null;
  trainingText?: string | null;
  trainingItems?:
    | {
        number: string;
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  scheduleEyebrow?: string | null;
  scheduleTitle?: string | null;
  scheduleText?: string | null;
  shopEyebrow?: string | null;
  shopTitle?: string | null;
  shopText?: string | null;
  shopButtonLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Présentation de Laëtitia affichée sur la page d’accueil.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "a-propos".
 */
export interface APropo {
  id: number;
  displayName?: string | null;
  role?: string | null;
  primaryText?: string | null;
  secondaryText?: string | null;
  /**
   * Sélectionnez une photo existante ou importez-en une nouvelle.
   */
  photo?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Coordonnées publiques, réseaux sociaux et informations pratiques.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coordonnees-site".
 */
export interface CoordonneesSite {
  id: number;
  businessName?: string | null;
  address?: string | null;
  postalCode?: string | null;
  city?: string | null;
  phone?: string | null;
  email?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  shopUrl?: string | null;
  appointmentText?: string | null;
  fundingText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accueil_select".
 */
export interface AccueilSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitleLine1?: T;
  heroTitleLine2?: T;
  heroTitleAccent?: T;
  heroText?: T;
  introEyebrow?: T;
  introTitle?: T;
  introText?: T;
  careEyebrow?: T;
  careLabel?: T;
  careTitle?: T;
  careText?: T;
  immersiveLine1?: T;
  immersiveLine2?: T;
  immersiveAccent?: T;
  trainingEyebrow?: T;
  trainingLabel?: T;
  trainingTitle?: T;
  trainingText?: T;
  trainingItems?:
    | T
    | {
        number?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  scheduleEyebrow?: T;
  scheduleTitle?: T;
  scheduleText?: T;
  shopEyebrow?: T;
  shopTitle?: T;
  shopText?: T;
  shopButtonLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "a-propos_select".
 */
export interface AProposSelect<T extends boolean = true> {
  displayName?: T;
  role?: T;
  primaryText?: T;
  secondaryText?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coordonnees-site_select".
 */
export interface CoordonneesSiteSelect<T extends boolean = true> {
  businessName?: T;
  address?: T;
  postalCode?: T;
  city?: T;
  phone?: T;
  email?: T;
  instagram?: T;
  facebook?: T;
  shopUrl?: T;
  appointmentText?: T;
  fundingText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}